llm_analytics:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: fillin
      user: fillin
      password: fillin
      role: ACCOUNTADMIN
      database: LLM_ANALYSIS
      warehouse: DEMO_WH
      schema: PUBLIC
      threads: 4
      client_session_keep_alive: False